### ISSUE TITLE
Documentation Redirects To GitBook Login

### ISSUE THREAD

**Issue by gfleetwood** [AppFlowy-IO/docs#1]
Your links on this page redirect to a request to sign into gitbook instead of to the subpages in the documentation:

https://appflowy.gitbook.io/docs/essential-documentation/install-appflowy/installation-methods

**Comment by MikeWallaceDev** [comment]
Fixed with Merge Request #39

**Comment by MikeWallaceDev** [comment]
Fixed in Gitbooks
